<h1 class="page-title">
	Data Generated by Dashboard

</h1>
<div class="clr"></div>
<div ng-controller="MainCtrl">
<h1 class="related">			
		  <span class="editHdng"><i class="fa fa-pencil-square-o vtip" title="You can enter/edit report title"></i></span>
		  <input type="text" id="diagnostic_name" name="diagnostic_name" value="" ng-model="name" placeholder="Enter Report title" maxlength="50">
		</h1>
	<div class="ylwRibbonHldr">
		<div class="tabitemsHldr">		
		</div>
	</div>
	<div class="subTabWorkspace pad26">
	<span><b><i>{{basis}}</i></b></span><br/>
	<span>{{filterString}}</span>
	<!-- <small><b>Note:-</b> <i>Values shown in cells represent no. of schools instead of  reviews in most of the cases except the two variables, external reviewer and Award where data will display no. of reviews.</i></small> -->	
		<div  style="padding-top:10px;">
			<div id="grid1" ui-grid="gridOptions" ui-grid-selection
				ui-grid-exporter class="grid"></div>
		</div>
	</div>
</div>